name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências (incluindo Cypress)
        run: |
          npm install
          npx cypress install

      - name: Listar arquivos de teste (debug)
        run: ls -la cypress/e2e/

      - name: Rodar testes Cypress
        run: npx cypress run --browser chrome --headless --spec "cypress/e2e/*.cy.js"
